name: sign_in_interface
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.2.1
  path_provider: ^2.0.11
  shared_preferences: ^2.0.15
  cupertino_icons: ^1.0.5
  http: ^0.13.5
  syncfusion_flutter_charts: ^20.3.48
  youtube_player_flutter: ^8.1.0
  timeline_list: ^0.0.6
  carousel_slider: ^4.1.1
  flutter_cache_manager: ^3.3.0
  snippet_coder_utils: ^1.0.12
  flutter_progress_hud: ^2.0.2
  dio: ^4.0.6
  custom_info_window: ^1.0.1
  flutter_tts: ^3.5.3
  email_validator: ^2.1.17
  fluttertoast: ^8.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/data/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: BubblegumSans
      fonts:
        - asset: fonts/BubblegumSans-Regular.ttf
    - family: BubblegumSans
      fonts:
        - asset: fonts/BalooDa2-Bold.ttf
        - asset: fonts/BalooDa2-ExtraBold.ttf
        - asset: fonts/BalooDa2-Medium.ttf
        - asset: fonts/BalooDa2-Regular.ttf
        - asset: fonts/BalooDa2-SemiBold.ttf
          # style: italic
    - family: Flavors
      fonts:
        - asset: fonts/Flavors-Regular.ttf
    - family: Langar-Regular
      fonts:
        - asset: fonts/Langar-Regular.ttf
    - family: ShinyBalloonDemo
      fonts:
        - asset: fonts/ShinyBalloonDemo.ttf
    - family: Langar-Regular
      fonts:
        - asset: fonts/Langar-Regular.ttf

  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
